### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by edos4** [dignajar/nibbleblog#96]
Please add the multi-user capability.

**Comment by dignajar** [comment]
Hi; try my new project Bludit.com
Support multi user.

**Comment by tommygunnz** [comment]
mulit-user is done, along with several enhancements and bug fixes.
finishing final regression testing, should be ready in a day or 2.
i can share a zip file, let me know.

**Comment by edos4** [comment]
@tommygunnz , may I request for the zip file please? Email is edsalinas7b@yahoo.com.

**Comment by tommygunnz** [comment]
manifest of fixes/improvements to 4.0.5 if anyone is interested:

fixed:
- FB and google shares now operative for supporting themes
- blank password no longer allowed on settings->accounts, caused user lockout
- blank username no longer allowed on settings->accounts
- blank email no longer allowed on settings->accounts
- inability to add website link to own site in a post now works
- default checkbox to allow comments on all posts maintains setting
- URL rewrites in seo.bit removed because they are incorrect and BREAK the blog in various ways
- simpler2 theme now showing any posted text for video blogs
- pager at bottom of manage pages admin screen only shows when more than 1 page of data exists.  also counting begins with '1' now for all multi-page displays
- new comment alert and comment entry form appearing at same time was causing missed comments.  precessing put in to allow only one or the other.
- HTML special characters in comments and author name were not displayed verbatim
- comments limited to 1000 characters and force-wrapped at end of comment textarea to prevent horizontal scrolling for long comments and ureadable admin control panels
- email 'validation' check now in place for user comment email address
- publishing comment with blank author name no longer allowed
- setting size of tag font now functioning

enhancements:
- multi-user, only difference between admin and normal user is that the administrator has the ability to add/remove users.  completely deleting user from users.xml not available, but can replace user with another by editing fields.
- mouseovers added for all admin panel active links/buttons
- username added to all post titles in simple2 theme and others
- simple2 theme improved
- ability to change user email address added
- confirmation now required for user password change on settings->accounts
- easy4 admin panel layout improved/enhanced
- native comment length now limited to 1000 characters
- native comments display as written by author, including carriage returns
- number of pages to display in page plugin now selectable in page pluging configuration
- deleting last post or page on manage->posts or manage->pages, then clicking last (and now invlid) pager link returns users to previous page of data

to do by others:
- add ability to restrict access of new users to specific blog features
- additional language support needed for all languages except english for all new/fixed functionality
- update.php and install.php may need slight mods
- regex RewriteRules in admin/views/settings/seo.bit for .htaccess are completely wrong and BREAK the blog in various ways if invoked.
- fix calls to defunct defensio to stop php from generating error_log warnings
- bump version number
